# Generated by Django 4.2 on 2025-02-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchasedetails',
            unique_together=set(),
        ),
    ]
