# Generated by Django 4.2 on 2025-02-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_manager', '0002_alter_purchasedetails_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensingdetails',
            name='fleet_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
