# Generated by Django 4.2 on 2025-02-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_manager', '0002_asset_purchasedetails_financingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetails',
            name='disc_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
